version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app
hooks:
  AfterInstall:
    - location: deploy/preparation.sh
      runas: root

permissions:
  - object: /var/www/app/deploy
    pattern: "**"
    owner: ec2-user
    group: nginx
    mode: 774
    type:
      - file
