version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/laravel-todo-api
hooks:
  AfterInstall:
    - location: scripts/preparation.sh
      runas: root

permissions:
  - object: /home/ec2-user/laravel-todo-api/scripts
    pattern: "**"
    owner: ec2-user
    group: nginx
    mode: 774
    type:
      - file