name: Continuous integration
on: [pull_request]

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, dom, fileinfo, mysql, gd, pdo, bcmath, json

      - name: Install Composer dependencies
        run: composer install --no-suggest --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.ci .env

      - name: Run lint
        run: vendor/bin/phpcs

  analyse:
    name: Static analysis check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, dom, fileinfo, mysql, gd, pdo, bcmath, json

      - name: Install Composer dependencies
        run: composer install --no-suggest --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.ci .env

      - name: Run analyse
        run: vendor/bin/phpstan analyze --error-format=github

  test:
    name: Test check
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: repo
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 --name mysql
        volumes:
          - ${{ github.workspace }}/conf.d:/etc/mysql/conf.d

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup php 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, dom, fileinfo, mysql, gd, pdo, bcmath, json

      - name: Install Composer dependencies
        run: composer install --no-suggest --prefer-dist --optimize-autoloader

      - name: Copy .env
        run: cp .env.ci .env.testing

      - name: Run migrate
        run: php artisan migrate --env=testing

      - name: Run test
        run: vendor/bin/phpunit
